In [11]:
import numpy as np

In [13]:
x = np.array(["A",40,34,42,4.3])
print(x)
print(type(x))
print(x.dtype)

['A' '40' '34' '42' '4.3']
<class 'numpy.ndarray'>
<U32


In [15]:
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [25]:
#Reshaping an array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [35]:
c = np.arange(3, 20)
print(c)
print(type(c))


[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [50]:


a1 = np.array([[3, 4, 5, 7], [4, 5, 8, np.nan]])
a1_copy1 = a1.astype(float)
a1_copy2 = a1_copy1.copy()

print(a1_copy2)
print(type(a1_copy2))


[[ 3.  4.  5.  7.]
 [ 4.  5.  8. nan]]
<class 'numpy.ndarray'>


In [46]:
a1 = np.array([[3,4,5,7],[4,5,8,np.NAN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  7.]
 [ 4.  5.  8. nan]]


dtype('float64')

In [54]:
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1


[['3.0' '4.0' '5.0' '7.0']
 ['4.0' '5.0' '8.0' 'nan']]


array([['3.0', '4.0', '5.0', '7.0'],
       ['4.0', '5.0', '8.0', 'nan']], dtype='<U32')

In [56]:
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [60]:
print(a2.sum(axis = 1))
print(a2.sum(axis=0))

[13 26 22]
[14 19 28]


In [62]:
print(a2)
print(np.mean(a2, axis =1))
print(np.mean(a2, axis =0))


[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[4.33333333 8.66666667 7.33333333]
[4.66666667 6.33333333 9.33333333]


In [3]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,4],[7,3]])
c = np.matmul(A,B)
print(c)


[[19 10]
 [43 24]]


In [5]:
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [4 3]]


In [7]:
a4 = np.array([[3,4,2],[7,4,5],[2,3,4],[4,2,5]])
a4

array([[3, 4, 2],
       [7, 4, 5],
       [2, 3, 4],
       [4, 2, 5]])

In [35]:
#slicing of array
a4[:,1:]

array([[4, 2],
       [4, 5],
       [3, 4],
       [2, 5]])

In [37]:
a4[1:,:]

array([[7, 4, 5],
       [2, 3, 4],
       [4, 2, 5]])

In [45]:
a4[2:,:]

array([[2, 3, 4],
       [4, 2, 5]])